name: Linting

on:
  pull_request:
    branches: [ main ]

jobs:
  markdown_lint:
    name: "Markdown linting"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
      - name: "Markdown linting"
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          config_file: .github/markdown-style-config.yml
          #debug: true
          exclude: |
            CHANGELOG.md
